# Site settings
title: UMN Student Degree Progress
email: asrweb@umn.edu
description: "UMN Student Degree Progress"
url: "http://umn-sdp.github.io"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
excerpt_separator: <!--break-->
exclude: ["bin","README.md", "bundle", "Gemfile", "Gemfile.lock"]

kramdown:
  input: GFM
  syntax_highlighter: pygments
